# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Bookmarks
    url: bookmarks/
    weight: 20
  - name: Notes
    url: notes/
    weight: 30
  - name: Notebooks
    url: notebooks/
    weight: 40
  - name: ZK
    url: zk/
    weight: 50
  - name: Tags
    url: tag-cloud/
    weight: 60
